"""change the title column in job to not be unique or nullable

Revision ID: 9562c8041fea
Revises: 2816b58b85f8
Create Date: 2023-06-25 14:08:54.633571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9562c8041fea'
down_revision = '2816b58b85f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_constraint('jobs_title_key', 'jobs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('jobs_title_key', 'jobs', ['title'])
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
