"""initial

Revision ID: a03cd9652913
Revises: 
Create Date: 2023-06-22 18:02:54.059267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03cd9652913'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=20), nullable=False),
    sa.Column('approvers', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('jobs', sa.ARRAY(sa.Integer()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('hourly_rate', sa.String(length=200), nullable=False),
    sa.Column('skills', sa.String(length=200), nullable=False),
    sa.Column('working_hours', sa.String(length=200), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('delivery', 'pet_sitter', 'scooter_charging', 'online_surveys', 'driver', 'translation', 'photography', 'cleaning', 'tutor', 'security_officer', 'nanny', 'other', name='category'), server_default='other', nullable=False),
    sa.Column('posted_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('candidate', 'approver', 'admin', name='roletype'), server_default='candidate', nullable=False),
    sa.Column('iban', sa.String(length=200), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('company_approvers',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('company_jobs',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_jobs')
    op.drop_table('company_approvers')
    op.drop_table('users')
    op.drop_table('jobs')
    op.drop_table('companies')
    # ### end Alembic commands ###
