"""add amount to job_user table

Revision ID: c219de673b55
Revises: d9bb7e09605e
Create Date: 2023-07-03 13:46:18.093744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c219de673b55'
down_revision = 'd9bb7e09605e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs_users', sa.Column('amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs_users', 'amount')
    # ### end Alembic commands ###
